#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles numericstepper" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="11" controlTypeID="com.balsamiq.mockups::NumericStepper" x="70" y="30" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>3</text>
          </controlProperties>
        </control>
        <control controlID="12" controlTypeID="com.balsamiq.mockups::NumericStepper" x="145" y="30" w="84" h="-1" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>3</text>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <link rel="stylesheet" type="text/css" href="numericstepper.css" />
      <script type = "text/javascript" src="basic.js"> </script>
      <script type = "text/javascript" src="numericstepper.js"> </script>
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="NumericStepper" id="NumericStepper11";
        style="position: absolute; font-size:12px; text-align: left; left: 70px; top: 30px; width: 41px; height: 22px;
        z-index: 0; overflow: hidden;">
        <p style="margin-left: 8px; margin-top: 2px;">3</p>
      <div class="NumericStepperbutton" id="NumericStepper11up";
          style="position: absolute; font-size:11px; text-align: center; left: 26px; top: 0px; width: 15px; height: 11px;
          z-index: 0;" onclick="Spinner.up('NumericStepper11');">
        <div style="position: relative; top: -3px; background-color: transparent; outline: none; z-index: 0;">
          <p><a>+</a></p>
        </div>
      </div>
      <div class="NumericStepperbutton" id="NumericStepper11down";
          style="position: absolute; font-size:11px; text-align: center; left: 26px; top: 11px; width: 15px; height: 11px;
          z-index: 0;" onclick="Spinner.down('NumericStepper11');">
        <div style="position: relative; top: -3px; background-color: transparent; outline: none; z-index: 0;">
          <p><a>-</a></p>
        </div>
      </div>
    </div>
    <div class="NumericStepper" id="NumericStepper12";
        style="position: absolute; font-size:12px; text-align: left; left: 145px; top: 30px; width: 84px; height: 22px;
        z-index: 1; overflow: hidden;">
        <p style="margin-left: 8px; margin-top: 2px;">3</p>
      <div class="NumericStepperbutton" id="NumericStepper12up";
          style="position: absolute; font-size:11px; text-align: center; left: 69px; top: 0px; width: 15px; height: 11px;
          z-index: 1;" onclick="Spinner.up('NumericStepper12');">
        <div style="position: relative; top: -3px; background-color: transparent; outline: none; z-index: 1;">
          <p><a>+</a></p>
        </div>
      </div>
      <div class="NumericStepperbutton" id="NumericStepper12down";
          style="position: absolute; font-size:11px; text-align: center; left: 69px; top: 11px; width: 15px; height: 11px;
          z-index: 1;" onclick="Spinner.down('NumericStepper12');">
        <div style="position: relative; top: -3px; background-color: transparent; outline: none; z-index: 1;">
          <p><a>-</a></p>
        </div>
      </div>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

.NumericStepperbutton a, a:hover, a:active {
  text-decoration: none;
  color: #010101;
}

.NumericStepperbutton:hover {
  background-color: #CCCCCC;
}

.NumericStepperbutton:active {
  background-color: #AAEEBB;
  margin-top: 2px;
}

    EOF
    js = <<-EOF

var Spinner =
{
  foo : "",
  up : function(id)
  {
    var div = document.getElementById(id);
    var elem = div.getElementsByTagName("p");
    var value = elem[0].innerText;
    value = parseInt(value);
    value++;
    elem[0].innerText = value.toString();
  },
  down : function(id)
  {
    var div = document.getElementById(id);
    var elem = div.getElementsByTagName("p");
    var value = elem[0].innerText;
    value = parseInt(value);
    value--;
    elem[0].innerText = value.toString();
  },
}

    EOF
    filename = "numericstepper"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
