#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles columnchart" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="9" controlTypeID="com.balsamiq.mockups::ColumnChart" x="192" y="14" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="10" controlTypeID="com.balsamiq.mockups::ColumnChart" x="166" y="60" w="391" h="392" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Generated by Balsamiq Exporter -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
          <link rel="stylesheet" type="text/css" href="reset.css" />
          <script type = "text/javascript" src="prototype.js"> </script>
          <script type = "text/javascript" src="basic.js"> </script>
          <script type = "text/javascript" src="columnchart.js"> </script>
        <title>Balsamiq</title>
        <script type="text/javascript">
          addLoadEvent(function() {draw_columnchart("ColumnChart9canvas", 187, 175, '[["#FF0101",0.45,0.8],["#0101FF",0.6,0.7]]')});

          addLoadEvent(function() {draw_columnchart("ColumnChart10canvas", 391, 392, '[["#FF0101",0.45,0.8],["#0101FF",0.6,0.7]]')});

        </script>
      </head>

      <body>
        <div class="ColumnChart" id="ColumnChart9"
            style="position: absolute; font-size:10pt; text-align: left; left: 192px; top: 14px; width: 187px; 
                   padding:5px; outline: none; color: #010101; background-color: transparent; z-index: 0">
         <canvas id="ColumnChart9canvas" width="187" height="175">
         </canvas>
        </div>
        <div class="ColumnChart" id="ColumnChart10"
            style="position: absolute; font-size:10pt; text-align: left; left: 166px; top: 60px; width: 391px; 
                   padding:5px; outline: none; color: #010101; background-color: transparent; z-index: 1">
         <canvas id="ColumnChart10canvas" width="391" height="392">
         </canvas>
        </div>
      </body>
    </html>
    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    function draw_columnchart(canvasid, w, h, json)
    {
    	var canvasel = document.getElementById(canvasid);
    	var ctx = canvasel.getContext('2d');

      ctx.fillStyle = "rgba(0,0,0,1.0)";
      ctx.strokeStyle = "rgba(0,0,0,1.0)";
      ctx.lineWidth = 8;
      ctx.lineCap = "round";
      ctx.fillRect(0,0,4,h);
      ctx.fillRect(0,h-4,w,h-4);

      var graphdata = json.evalJSON(true);
      var bars = graphdata.length;
      // first item is color
      var items = graphdata[0].length - 1;

      var percent = 1.0/((bars+1)*items+1);

      ctx.lineWidth = 2;

      var bar;
      var item;

      for (item = 1; item <= items; item++)
      {
        for (bar = 0; bar < bars; bar++)
        {
          ctx.fillStyle = graphdata[bar][0];
          ctx.fillRect(w*percent*(bar+(item-1)*3+1),h*(1.0-graphdata[bar][item]),percent*w,h*graphdata[bar][item]-2);
          ctx.strokeRect(w*percent*(bar+(item-1)*3+1),h*(1.0-graphdata[bar][item]),percent*w,h*graphdata[bar][item]-2);
        }        
      }
    }
    EOF
    filename = "columnchart"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
