#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles tabbar" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="34" controlTypeID="com.balsamiq.mockups::TabBar" x="37" y="36" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>One%2C%20Two%2C%20Three%2C%20Four</text>
          </controlProperties>
        </control>
        <control controlID="35" controlTypeID="com.balsamiq.mockups::TabBar" x="40" y="171" w="368" h="250" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>One%2C%20Two%2C%20Three%2C%20Four%2C%20Five%2C%20Six</text>
            <tabVPosition>bottom</tabVPosition>
            <tabHPosition>center</tabHPosition>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <link rel="stylesheet" type="text/css" href="tabbar.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="TabBar" id="TabBar34"
          style="position: absolute; left: 37px; top: 36px; height: 100px; width: 256px; z-index: 0;">
      <div style="position: absolute; left: 0px; top: -22px; height: 20px; width: 256px; z-index: 0;
                  outline: none; background-color: transparent;">
    <div class="TabBar" id="TabBar34tab"
          style="position: absolute; left: 0px; top: 0px; height: 20px; z-index: 0;
          font-size:10pt; outline: none; background-color: transparent;">
      <div class="TabBar" id="TabBar34tab_0"
          style="float: left; height: 20px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 0;
                 font-size:10pt; height: 17px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">One</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 1;
             font-size:10pt; top: -20px; height: 17px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">One</p></a>
        </div>
      </div>
      <div class="TabBar" id="TabBar34tab_1"
          style="float: left; height: 20px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 0;
                 font-size:10pt; height: 17px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Two</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 1;
             font-size:10pt; top: -20px; height: 17px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Two</p></a>
        </div>
      </div>
      <div class="TabBar" id="TabBar34tab_2"
          style="float: left; height: 20px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 0;
                 font-size:10pt; height: 17px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Three</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 1;
             font-size:10pt; top: -20px; height: 17px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Three</p></a>
        </div>
      </div>
      <div class="TabBar" id="TabBar34tab_3"
          style="float: left; height: 20px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 0;
                 font-size:10pt; height: 17px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Four</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 1;
             font-size:10pt; top: -20px; height: 17px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Four</p></a>
        </div>
      </div>
    </div>
</div></div>    <div class="TabBar" id="TabBar35"
          style="position: absolute; left: 40px; top: 171px; height: 250px; width: 368px; z-index: 1;">
      <div style="position: absolute; left: 0px; top: 255px; height: 20px; width: 368px; z-index: 1;
                  outline: none; background-color: transparent;">
    <div class="TabBar" id="TabBar35tab"
          style="position: absolute; left: 0px; top: 0px; height: 20px; z-index: 1;
          font-size:10pt; outline: none; background-color: transparent;">
      <div class="TabBar" id="TabBar35tab_0"
          style="float: left; height: 20px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 1;
                 font-size:10pt; height: 17px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">One</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 2;
             font-size:10pt; top: -20px; height: 17px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">One</p></a>
        </div>
      </div>
      <div class="TabBar" id="TabBar35tab_1"
          style="float: left; height: 20px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 1;
                 font-size:10pt; height: 17px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Two</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 2;
             font-size:10pt; top: -20px; height: 17px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Two</p></a>
        </div>
      </div>
      <div class="TabBar" id="TabBar35tab_2"
          style="float: left; height: 20px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 1;
                 font-size:10pt; height: 17px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Three</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 2;
             font-size:10pt; top: -20px; height: 17px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Three</p></a>
        </div>
      </div>
      <div class="TabBar" id="TabBar35tab_3"
          style="float: left; height: 20px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 1;
                 font-size:10pt; height: 17px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Four</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 2;
             font-size:10pt; top: -20px; height: 17px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Four</p></a>
        </div>
      </div>
      <div class="TabBar" id="TabBar35tab_4"
          style="float: left; height: 20px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 1;
                 font-size:10pt; height: 17px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Five</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 2;
             font-size:10pt; top: -20px; height: 17px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Five</p></a>
        </div>
      </div>
      <div class="TabBar" id="TabBar35tab_5"
          style="float: left; height: 20px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 1;
                 font-size:10pt; height: 17px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Six</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 2;
             font-size:10pt; top: -20px; height: 17px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Six</p></a>
        </div>
      </div>
    </div>
</div></div>  </body>
</html>

    EOF
    css = <<-EOF
    .balsamiq_button a, a:hover, a:active {
  text-decoration: none;
  color: #010101;
}

.balsamiq_button:hover {
  background-color: #CCCCCC;
}

.balsamiq_button:active {
  background-color: #AAEEBB;
  margin-top: 2px;
}

    EOF
    js = <<-EOF
    /* Generated by Balsamiq Exporter
/* Simon Willison's cool hack to build out multiple onload events */
function addLoadEvent(func) 
{
  var oldonload = window.onload;
  if (typeof window.onload != 'function') 
  {
    window.onload = func;
  } 
  else 
  {
    window.onload = function() 
    {
      if (oldonload) 
      {
        oldonload();
      }
      func();
    }
  }
}

    EOF
    filename = "tabbar"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
