#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles hrule" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="8" controlTypeID="com.balsamiq.mockups::HRule" x="29" y="16" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="9" controlTypeID="com.balsamiq.mockups::HRule" x="30" y="32" w="223" h="-1" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="HRule" id="HRule8" 
          style="position: absolute; left: 29px; top: 16px; width: 100px; height: 2px;
          font-size:10pt; outline: none; background-color: #010101;">
    </div>
    <div class="HRule" id="HRule9" 
          style="position: absolute; left: 30px; top: 32px; width: 223px; height: 2px;
          font-size:10pt; outline: none; background-color: #010101;">
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    EOF
    filename = "hrule"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
