#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles button" do
    data = <<-EOF
        <mockup version="1.0" skin="sketch">
  <controls>
    <control controlID="13" controlTypeID="com.balsamiq.mockups::Button" x="36" y="59" w="-1" h="-1" zOrder="2" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Very%2C%20very%2C%20very%20long%20button</text>
      </controlProperties>
    </control>
    <control controlID="6" controlTypeID="com.balsamiq.mockups::Button" x="36" y="22" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Button</text>
      </controlProperties>
    </control>
    <control controlID="7" controlTypeID="com.balsamiq.mockups::Button" x="116" y="22" w="148" h="-1" zOrder="1" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Big%20Button</text>
      </controlProperties>
    </control>
  </controls>
</mockup>    


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <link rel="stylesheet" type="text/css" href="button.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="Button" id="Button13"
          style="position: absolute; left: 36px; top: 59px; height: 22px; z-index: 2;
          font-size:10pt; outline: none; background-color: transparent;">
      <div class="Button" id="Button13_0"
          style="float: left; height: 22px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 2;
                 font-size:10pt; height: 19px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Very, very, very long button</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 3;
             font-size:10pt; top: -22px; height: 19px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Very, very, very long button</p></a>
        </div>
      </div>
    </div>
    <div class="Button" id="Button6"
          style="position: absolute; left: 36px; top: 22px; height: 22px; z-index: 0;
          font-size:10pt; outline: none; background-color: transparent;">
      <div class="Button" id="Button6_0"
          style="float: left; height: 22px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 0;
                 font-size:10pt; height: 19px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Button</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 1;
             font-size:10pt; top: -22px; height: 19px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Button</p></a>
        </div>
      </div>
    </div>
    <div class="Button" id="Button7"
          style="position: absolute; left: 116px; top: 22px; height: 22px; z-index: 1;
          font-size:10pt; outline: none; background-color: transparent;">
      <div class="Button" id="Button7_0"
          style="float: left; height: 22px; outline: none; padding-right:3px; background-color: transparent;">
        <div class="balsamiq_shadow"
          style="position: relative; top: 3px; left: 3px; z-index: 1;
                 font-size:10pt; height: 19px; outline: 2px solid #010101; background-color:#010101;">
          <p style="padding-left:10px;padding-right:10px;">Big Button</p>
        </div>
        <div class="balsamiq_button"
          style = "position: relative; z-index: 2;
             font-size:10pt; top: -22px; height: 19px;">
          <a href=""><p style="padding-left:10px;padding-right:10px;">Big Button</p></a>
        </div>
      </div>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    .balsamiq_button a, a:hover, a:active {
  text-decoration: none;
  color: #010101;
}

.balsamiq_button:hover {
  background-color: #CCCCCC;
}

.balsamiq_button:active {
  background-color: #AAEEBB;
  margin-top: 2px;
}

    EOF
    js = <<-EOF

    EOF
    filename = "button"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
