#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles menu" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="0" controlTypeID="com.balsamiq.mockups::Menu" x="21" y="17" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Open%2CCTRL+O%0AOpen%20Recent%20%3E%0A---%0Ao%20Option%20One%0AOption%20Two%0A%3D%0Ax%20Show%20Something%0AExit%2CCTRL+Q</text>
          </controlProperties>
        </control>
        <control controlID="1" controlTypeID="com.balsamiq.mockups::Menu" x="218" y="22" w="341" h="-1" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Open%2CCTRL+O%0AOpen%20Recent%20%3E%0A---%0Ao%20Option%20One%0AOption%20Two%0A%3D%0Ax%20Show%20Something%0AExit%2CCTRL+Q%0A---%0ADo%20something%20else%21</text>
          </controlProperties>
        </control>
      </controls>
    </mockup>   


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <link rel="stylesheet" type="text/css" href="menu.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="Menu" id="Menu0"
        style="position: absolute; left: 21px; top: 17px; width:150px;
        z-index: 0; background-color: transparent; ">
        <table cellspacing="0" style="border-collapse: collapse; border-spacing: 0; width:100%; height:100%">
        <tr><td class='left'></td><td class='middle'>Open</td><td class='right'>CTRL O</td></tr>
<tr><td class='left'></td><td class='middle'>Open Recent </td><td class='right'>></td></tr>
<tr><td colspan='3'>---------------------</td></tr>
<tr><td class='left'>o</td><td class='middle'>Option One</td><td class='right'></td></tr>
<tr><td class='left'></td><td class='middle'>Option Two</td><td class='right'></td></tr>
<tr><td colspan='3'>---------------------</td></tr>
<tr><td class='left'>x</td><td class='middle'>Show Something</td><td class='right'></td></tr>
<tr><td class='left'></td><td class='middle'>Exit</td><td class='right'>CTRL Q</td></tr>

        </table>
    </div>
    <div class="Menu" id="Menu1"
        style="position: absolute; left: 218px; top: 22px; width:341px;
        z-index: 1; background-color: transparent; ">
        <table cellspacing="0" style="border-collapse: collapse; border-spacing: 0; width:100%; height:100%">
        <tr><td class='left'></td><td class='middle'>Open</td><td class='right'>CTRL O</td></tr>
<tr><td class='left'></td><td class='middle'>Open Recent </td><td class='right'>></td></tr>
<tr><td colspan='3'>---------------------</td></tr>
<tr><td class='left'>o</td><td class='middle'>Option One</td><td class='right'></td></tr>
<tr><td class='left'></td><td class='middle'>Option Two</td><td class='right'></td></tr>
<tr><td colspan='3'>---------------------</td></tr>
<tr><td class='left'>x</td><td class='middle'>Show Something</td><td class='right'></td></tr>
<tr><td class='left'></td><td class='middle'>Exit</td><td class='right'>CTRL Q</td></tr>
<tr><td colspan='3'>---------------------</td></tr>
<tr><td class='left'></td><td class='middle'>Do something else!</td><td class='right'></td></tr>

        </table>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    .{c[:controlTypeID]} .left {
  font-size: 9pt;
  text-align: left;
  width: 10px;
}

.{c[:controlTypeID]} .middle {
  font-size: 9pt;
  text-align: left;
  width: 55%;
}

.{c[:controlTypeID]} .right {
  font-size: 9pt;
  text-align: right;
}
.{c[:controlTypeID]} .left {
  font-size: 9pt;
  text-align: left;
  width: 10px;
}

.{c[:controlTypeID]} .middle {
  font-size: 9pt;
  text-align: left;
  width: 55%;
}

.{c[:controlTypeID]} .right {
  font-size: 9pt;
  text-align: right;
}

    EOF
    js = <<-EOF

    EOF
    filename = "menu"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
