#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles tree" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="47" controlTypeID="com.balsamiq.mockups::Tree" x="33" y="12" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>f%20Use%20f%20for%20closed%20folders%0AF%20Use%20F%20for%20open%20folders%0A%20-%20Use%20-%20for%20files%0AF%20Use%20spaces%2C%20dots%20or%20%3E%20for%20hierarchy%0A%20-%20like%20this%20%28a%20file%20in%20a%20folder%29%0A.F%20and%20this%20%28a%20subfolder%29%0A%3E%3E-%20a%20file%20in%20a%20subfolder%0A-%20you%27ll%20get%20the%20hang%20of%20it</text>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="Tree" id="Tree47"
        style="position: absolute; text-align: left; left: 33px; top: 12px; width:280px;
        z-index: 0;">
        <p>f Use f for closed folders</p>
<p>F Use F for open folders</p>
<p>&nbsp;&nbsp;- Use - for files</p>
<p>F Use spaces, dots or > for hierarchy</p>
<p>&nbsp;&nbsp;- like this (a file in a folder)</p>
<p>&nbsp;&nbsp;F and this (a subfolder)</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;- a file in a subfolder</p>
<p>- you'll get the hang of it</p>

    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    /* Generated by Balsamiq Exporter */
* {
  vertical-align: baseline;
  font-weight: inherit;
  font-family: inherit;
  font-style: inherit;
  font-size: 100%;
  border: 0 none;
  outline: 0;
  padding: 0;
  margin: 0;
}

body {
  background-color: #f8f4ed;
  font-family: "Comic Sans MS", Arial,sans-serif;
  color: #010101;
}

div {
  background-color: #ffffff;
  outline: 2px solid #202028;
  text-align: center;
}

a {
  color:#0101ff;
}

a:link {
  color:#0101ff;
}

a:hover {
  color:#FD0101;
}

    EOF
    js = <<-EOF
    /* Generated by Balsamiq Exporter
/* Simon Willison's cool hack to build out multiple onload events */
function addLoadEvent(func) 
{
  var oldonload = window.onload;
  if (typeof window.onload != 'function') 
  {
    window.onload = func;
  } 
  else 
  {
    window.onload = function() 
    {
      if (oldonload) 
      {
        oldonload();
      }
      func();
    }
  }
}

    EOF
    filename = "tree"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
