#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles canvas" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="22" controlTypeID="com.balsamiq.mockups::Canvas" x="51" y="24" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="23" controlTypeID="com.balsamiq.mockups::Canvas" x="187" y="26" w="210" h="203" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <backgroundAlpha>0.5</backgroundAlpha>
            <color>16711680</color>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="Canvas" id="Canvas22"
        style="position: absolute; left: 51px; top: 24px; width: 100px; height: 70px;
        z-index: 0; background-color: transparent;">
      <div class="Canvas"
          style="position: absolute; left:0px; top:0px; width: 100px; height: 70px;
            z-index: 0; outline: none; background-color: RGBA(255,255,255,1.0); opacity: 1.0";>
      </div>
    </div>
    <div class="Canvas" id="Canvas23"
        style="position: absolute; left: 187px; top: 26px; width: 210px; height: 203px;
        z-index: 1; background-color: transparent;">
      <div class="Canvas"
          style="position: absolute; left:0px; top:0px; width: 210px; height: 203px;
            z-index: 1; outline: none; background-color: rgba(255,0,0,1.0); opacity: 0.5";>
      </div>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    /* Generated by Balsamiq Exporter */
* {
  vertical-align: baseline;
  font-weight: inherit;
  font-family: inherit;
  font-style: inherit;
  font-size: 100%;
  border: 0 none;
  outline: 0;
  padding: 0;
  margin: 0;
}

body {
  background-color: #f8f4ed;
  font-family: "Comic Sans MS", Arial,sans-serif;
  color: #010101;
}

div {
  background-color: #ffffff;
  outline: 2px solid #202028;
  text-align: center;
}

a {
  color:#0101ff;
}

a:link {
  color:#0101ff;
}

a:hover {
  color:#FD0101;
}

    EOF
    js = <<-EOF
    /* Generated by Balsamiq Exporter
/* Simon Willison's cool hack to build out multiple onload events */
function addLoadEvent(func) 
{
  var oldonload = window.onload;
  if (typeof window.onload != 'function') 
  {
    window.onload = func;
  } 
  else 
  {
    window.onload = function() 
    {
      if (oldonload) 
      {
        oldonload();
      }
      func();
    }
  }
}

    EOF
    filename = "canvas"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
