#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles formattingtoolbar" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="3" controlTypeID="com.balsamiq.mockups::FormattingToolbar" x="13" y="40" w="397" h="-1" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="4" controlTypeID="com.balsamiq.mockups::FormattingToolbar" x="13" y="3" w="-1" h="-1" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>    


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="FormattingToolbar" id="FormattingToolbar3" 
          style="position: absolute; left: 13px; top: 40px; width: 397px; height: 29px;
          font-size:12pt; ">
      Formatting Toolbar
    </div>
    <div class="FormattingToolbar" id="FormattingToolbar4" 
          style="position: absolute; left: 13px; top: 3px; width: 270px; height: 29px;
          font-size:12pt; ">
      Formatting Toolbar
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    EOF
    filename = "formattingtoolbar"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
