#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles horizontalscrollbar" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="13" controlTypeID="com.balsamiq.mockups::HorizontalScrollBar" x="29" y="18" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="14" controlTypeID="com.balsamiq.mockups::HorizontalScrollBar" x="144" y="18" w="350" h="-1" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="HorizontalScrollBar" id="HorizontalScrollBar13"
        style="position: absolute; font-size:10pt; text-align: left; left: 29px; top: 18px; width: 100px; height: 15px; z-index: 0">
    </div>
    <div class="HorizontalScrollBar" id="HorizontalScrollBar14"
        style="position: absolute; font-size:10pt; text-align: left; left: 144px; top: 18px; width: 350px; height: 15px; z-index: 1">
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    EOF
    filename = "horizontalscrollbar"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
