#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles browserwindow" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="4" controlTypeID="com.balsamiq.mockups::BrowserWindow" x="23" y="10" w="425" h="295" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>A%20Web%20Page</text>
          </controlProperties>
        </control>
        <control controlID="5" controlTypeID="com.balsamiq.mockups::BrowserWindow" x="458" y="11" w="-1" h="-1" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>A%20Web%20Page</text>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <script type = "text/javascript" src="basic.js"> </script>
      <script type = "text/javascript" src="browserwindow.js"> </script>
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="BrowserWindow" id="BrowserWindow4" 
        style="position: absolute; left: 23px; top: 10px; 
        width: 425px; height: 295px; z-index: 0;background-color:#CCCCCC;}">
        <div style="height:20%; background-color:#CCCCCC; background-color:transparent; outline:none" >
          <div id="BrowserWindow4back" style="background-color:transparent; outline:none; height:100%; width:10%; float:left" onclick="CallStack.back('BrowserWindow4iframe');">
            <p>
              back
            </p>
          </div>
          <div id="BrowserWindow4fwd" style="background-color:transparent; outline:none; height:100%; width:10%; float:left" onclick="CallStack.fwd('BrowserWindow4iframe');">
            <p>
              fwd
            </p>
          </div>
          <div style="background-color:transparent; outline:none; height:100%; width:50%; float:left">
            <p>
              <input name=search type="text" size=20 onKeyPress="CallStack.browser('BrowserWindow4iframe', this,event, false);"></input>
            </p>
          </div>
          <div style="background-color:transparent; outline:none; height:100%; width:30%; float:left">
            <p>
              <input name=search type="text" size=8 onKeyPress="CallStack.browser('BrowserWindow4iframe', this, event, true);"></input>
            </p>
          </div>
        </div>
        <div style="height:70%; background-color:transparent; outline:none;"><iframe  id="BrowserWindow4iframe" height="99%" width="99%" frameborder=0 src="http://google.com"></iframe></div>
        <div style="height:10%; background-color:transparent; outline:none"></div>
    </div>
    <div class="BrowserWindow" id="BrowserWindow5" 
        style="position: absolute; left: 458px; top: 11px; 
        width: 450px; height: 400px; z-index: 1;background-color:#CCCCCC;}">
        <div style="height:20%; background-color:#CCCCCC; background-color:transparent; outline:none" >
          <div id="BrowserWindow5back" style="background-color:transparent; outline:none; height:100%; width:10%; float:left" onclick="CallStack.back('BrowserWindow5iframe');">
            <p>
              back
            </p>
          </div>
          <div id="BrowserWindow5fwd" style="background-color:transparent; outline:none; height:100%; width:10%; float:left" onclick="CallStack.fwd('BrowserWindow5iframe');">
            <p>
              fwd
            </p>
          </div>
          <div style="background-color:transparent; outline:none; height:100%; width:50%; float:left">
            <p>
              <input name=search type="text" size=20 onKeyPress="CallStack.browser('BrowserWindow5iframe', this,event, false);"></input>
            </p>
          </div>
          <div style="background-color:transparent; outline:none; height:100%; width:30%; float:left">
            <p>
              <input name=search type="text" size=8 onKeyPress="CallStack.browser('BrowserWindow5iframe', this, event, true);"></input>
            </p>
          </div>
        </div>
        <div style="height:70%; background-color:transparent; outline:none;"><iframe  id="BrowserWindow5iframe" height="99%" width="99%" frameborder=0 src="http://google.com"></iframe></div>
        <div style="height:10%; background-color:transparent; outline:none"></div>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    /* Generated by Balsamiq Exporter */
* {
  vertical-align: baseline;
  font-weight: inherit;
  font-family: inherit;
  font-style: inherit;
  font-size: 100%;
  border: 0 none;
  outline: 0;
  padding: 0;
  margin: 0;
}

body {
  background-color: #f8f4ed;
  font-family: "Comic Sans MS", Arial,sans-serif;
  color: #010101;
}

div {
  background-color: #ffffff;
  outline: 2px solid #202028;
  text-align: center;
}

a {
  color:#0101ff;
}

a:link {
  color:#0101ff;
}

a:hover {
  color:#FD0101;
}

    EOF
    js = <<-EOF

var CallStack =
{
  visits : {},
  popped : {},
  current : "http://google.com",

  timerid : 0,

  add : function(id, site)
  {
    if (!this.visits[id])
      this.visits[id] = [];
    this.visits[id].unshift(site);
  },

  // fwd means:
  //  current->visited, popped->current
  fwd : function(id)
  {
    if (!this.popped[id])
      this.popped[id] = [];
    if (this.popped[id].length > 0)
    {
      if (!this.visits[id])
        this.visits[id] = [];
      this.visits[id].unshift(this.current);
      this.current = this.popped[id].shift();
      document.getElementById(id).src = this.current;
    }
  },

  // back means:
  //  current->popped, visited->current
  back : function(id)
  {
    if (!this.visits[id])
      this.visits[id] = [];
    if (this.visits[id].length > 0)
    {
      if (!this.popped[id])
        this.popped[id] = [];
      this.popped[id].unshift(this.current);
      this.current = this.visits[id].shift();
      document.getElementById(id).src = this.current;
    }
  },

  seturl : function(id, url)
  {
    if (this.current != "")
      this.add(id, this.current);
    this.current = url;
    document.getElementById(id).src = url;
  },

  browser : function(id, searchform,event,search) 
  {
    var kc;
    if (window.event)
    {
      kc = window.event.keyCode;
    }
    else
    {
      if (event) 
        kc = e.which;
      else 
        return;
    } 

    if (kc == 13)
    {
      if (search)
      {
        var deststr = "http://www.google.com/search?client=safari&rls=en-us&ie=UTF-8&oe=UTF-8&q=" + searchform.value;
        this.seturl(id, deststr);
      }
      else
      {
        var urlexp = /(http|file):////.*/
        var result = urlexp.exec(searchform.value);
        var deststr;
        if (result)
          deststr = escape(searchform.value);
        else
          deststr = "http://" + searchform.value;
        this.seturl(id, deststr);
      }
    }
  }  
}

    EOF
    filename = "browserwindow"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
