#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles linechart" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="11" controlTypeID="com.balsamiq.mockups::LineChart" x="102" y="34" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="12" controlTypeID="com.balsamiq.mockups::LineChart" x="80" y="231" w="859" h="175" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Generated by Balsamiq Exporter -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
          <link rel="stylesheet" type="text/css" href="reset.css" />
          <script type = "text/javascript" src="prototype.js"> </script>
          <script type = "text/javascript" src="basic.js"> </script>
          <script type = "text/javascript" src="linechart.js"> </script>
        <title>Balsamiq</title>
        <script type="text/javascript">
          addLoadEvent(function() {draw_linechart("LineChart11canvas", 187, 175, '[["#FF0101",0,0.6,0.4,0.8],["#0101FF",0.3,0.4,0.8,0.6]]')});

          addLoadEvent(function() {draw_linechart("LineChart12canvas", 859, 175, '[["#FF0101",0,0.6,0.4,0.8],["#0101FF",0.3,0.4,0.8,0.6]]')});

        </script>
      </head>

      <body>
        <div class="" id="LineChart11"
            style="position: absolute; font-size:10pt; text-align: left; left: 102px; top: 34px; width: 187px; 
                   padding:5px; outline: none; color: #010101; background-color: transparent; z-index: 0">
         <canvas id="LineChart11canvas" width="187" height="175">
         </canvas>
        </div>
        <div class="" id="LineChart12"
            style="position: absolute; font-size:10pt; text-align: left; left: 80px; top: 231px; width: 859px; 
                   padding:5px; outline: none; color: #010101; background-color: transparent; z-index: 1">
         <canvas id="LineChart12canvas" width="859" height="175">
         </canvas>
        </div>
      </body>
    </html>
    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    function draw_linechart(canvasid, w, h, json)
    {
    	var canvasel = document.getElementById(canvasid);
    	var ctx = canvasel.getContext('2d');

      ctx.fillStyle = "rgba(0,0,0,1.0)";
      ctx.strokeStyle = "rgba(0,0,0,1.0)";
      ctx.lineWidth = 8;
      ctx.lineCap = "round";
      ctx.fillRect(0,0,4,h);
      ctx.fillRect(0,h-4,w,h-4);

      var graphdata = json.evalJSON(true);
      var itypes = graphdata.length;
      // first item is color
      var items = graphdata[0].length - 1;

      ctx.lineWidth = 2;
      var percent = 1.0/(items-1);

      var itype;
      var item;

      for (itype = 0; itype < itypes; itype++)
      {
        ctx.strokeStyle = graphdata[itype][0];
        ctx.beginPath();
        ctx.moveTo(4,h*(1-graphdata[itype][1]));
        for (item = 2; item <= items; item++)
        {
          ctx.lineTo((item-1)*percent*w,h*(1-graphdata[itype][item]));
        }
        ctx.stroke();
      }
    }
    EOF
    filename = "linechart"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
