#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles fieldset" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="26" controlTypeID="com.balsamiq.mockups::FieldSet" x="87" y="31" w="491" h="344" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>A%20group%21</text>
          </controlProperties>
        </control>
        <control controlID="27" controlTypeID="com.balsamiq.mockups::FieldSet" x="609" y="39" w="-1" h="-1" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Group%20Name</text>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="FieldSet" id="FieldSet26" 
          style="position: absolute; left: 87px; top: 31px; width: 491px; height: 344px;
          font-size:10pt; background-color: transparent;">
      <div style="position: absolute; left: 10px; top: -14px; padding: 4px">A group!</div>
    </div>
    <div class="FieldSet" id="FieldSet27" 
          style="position: absolute; left: 609px; top: 39px; width: 200px; height: 170px;
          font-size:10pt; background-color: transparent;">
      <div style="position: absolute; left: 10px; top: -14px; padding: 4px">Group Name</div>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    EOF
    filename = "fieldset"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
