#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles scratchout" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="28" controlTypeID="com.balsamiq.mockups::ScratchOut" x="29" y="17" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="29" controlTypeID="com.balsamiq.mockups::ScratchOut" x="37" y="139" w="516" h="148" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Generated by Balsamiq Exporter -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <link rel="stylesheet" type="text/css" href="reset.css" />
          <link rel="stylesheet" type="text/css" href="scratchout.css" />
          <script type = "text/javascript" src="basic.js"> </script>
          <script type = "text/javascript" src="scratchout.js"> </script>
        <title>Balsamiq</title>
        <script type="text/javascript">
          addLoadEvent(function() {draw_scratch_out("ScratchOut28canvas", 205, 107)});

          addLoadEvent(function() {draw_scratch_out("ScratchOut29canvas", 516, 148)});

        </script>
      </head>

      <body>
        <div class="ScratchOut" id="ScratchOut28"
            style="position: absolute; left: 29px; top: 17px; background-color: transparent; outline: none; z-index: 0">
          <canvas width="205" height="107" id="ScratchOut28canvas"></canvas>
        </div>
        <div class="ScratchOut" id="ScratchOut29"
            style="position: absolute; left: 37px; top: 139px; background-color: transparent; outline: none; z-index: 1">
          <canvas width="516" height="148" id="ScratchOut29canvas"></canvas>
        </div>
      </body>
    </html>
    EOF
    css = <<-EOF

.ScratchOut {
	background-color: transparent;
	outline: none
}

canvas {
	background-color: transparent;
}

    EOF
    js = <<-EOF

function draw_scratch_out(id, width, height)
{
  var canvas = document.getElementById(id);
  var ctx = canvas.getContext('2d');
  ctx.strokeStyle = "RGBA(1,1,1,1.0)";
  ctx.lineWidth = 8;
  var slope = height/width;
  var diagonal = Math.sqrt(height*height + width*width);
  var i;
  ctx.lineCap = "round";
	ctx.moveTo(0,0);
  var sine;
  for (i = 0; i < diagonal; i++)
  {
    if (i < diagonal/2)
      sine = Math.sin(i/4)*i*0.8;
    else
      sine = Math.sin(i/4)*(diagonal - i)*0.8;

    var xoffset = -sine*slope;
    var yoffset = sine*slope;
  	ctx.lineTo(i/diagonal*width + xoffset,i/diagonal*height+yoffset);
  }
	ctx.stroke();
}

    EOF
    filename = "scratchout"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
