#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles redx" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="24" controlTypeID="com.balsamiq.mockups::RedX" x="76" y="35" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="25" controlTypeID="com.balsamiq.mockups::RedX" x="145" y="139" w="186" h="260" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Generated by Balsamiq Exporter -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <link rel="stylesheet" type="text/css" href="reset.css" />
          <link rel="stylesheet" type="text/css" href="redx.css" />
          <script type = "text/javascript" src="basic.js"> </script>
          <script type = "text/javascript" src="redx.js"> </script>
        <title>Balsamiq</title>
        <script type="text/javascript">
          addLoadEvent(function() {draw_redx("RedX24canvas", 240, 104)});

          addLoadEvent(function() {draw_redx("RedX25canvas", 186, 260)});

        </script>
      </head>

      <body>
        <div class="RedX" id="RedX24"
            style="position: absolute; left: 76px; top: 35px; background-color: transparent; outline: none; z-index: 0">
          <canvas width="240" height="104" id="RedX24canvas"></canvas>
        </div>
        <div class="RedX" id="RedX25"
            style="position: absolute; left: 145px; top: 139px; background-color: transparent; outline: none; z-index: 1">
          <canvas width="186" height="260" id="RedX25canvas"></canvas>
        </div>
      </body>
    </html>
    EOF
    css = <<-EOF

.RedX {
	background-color: transparent;
	outline: none
}

canvas {
	background-color: transparent;
}

    EOF
    js = <<-EOF

function draw_redx(id, width, height)
{
  var canvas = document.getElementById(id);
  var ctx = canvas.getContext('2d');
  ctx.strokeStyle = "RGBA(120,22,29,1.0)";
  ctx.lineWidth = 16;
  ctx.lineCap = "round";
	ctx.moveTo(10,10);
	ctx.lineTo(width - 10,height - 10);
	ctx.moveTo(10,height-10);
	ctx.lineTo(width-10,10);
	ctx.stroke();
}

    EOF
    filename = "redx"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
