#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles image" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="11" controlTypeID="com.balsamiq.mockups::Image" x="70" y="11" w="213" h="241" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="12" controlTypeID="com.balsamiq.mockups::Image" x="319" y="22" w="-1" h="-1" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="Image" id="Image11"
        style="position: absolute; font-size:10pt; text-align: left; left: 70px; top: 11px; width: 213px; height: 241px; z-index: 0">
    </div>
    <div class="Image" id="Image12"
        style="position: absolute; font-size:10pt; text-align: left; left: 319px; top: 22px; width: 141px; height: 144px; z-index: 1">
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    EOF
    filename = "image"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
