#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles stickynote" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="22" controlTypeID="com.balsamiq.mockups::StickyNote" x="196" y="86" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>a%20comment%0Ano%2C%20really%2C%20a%20comment%21</text>
          </controlProperties>
        </control>
        <control controlID="23" controlTypeID="com.balsamiq.mockups::StickyNote" x="80" y="34" w="-1" h="-1" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>A%20comment</text>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="StickyNote" id="StickyNote22" 
          style="position: absolute; left: 196px; top: 86px; width: 109px; height: 123px; z-index: 0;
          font-size:10pt; background-color: rgba(252,251,94,1.0);">
      a comment
no, really, a comment!
    </div>
    <div class="StickyNote" id="StickyNote23" 
          style="position: absolute; left: 80px; top: 34px; width: 109px; height: 123px; z-index: 1;
          font-size:10pt; background-color: rgba(252,251,94,1.0);">
      A comment
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    EOF
    filename = "stickynote"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
