#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles barchart" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="4" controlTypeID="com.balsamiq.mockups::BarChart" x="18" y="11" w="233" h="106" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="6" controlTypeID="com.balsamiq.mockups::BarChart" x="266" y="35" w="155" h="252" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Generated by Balsamiq Exporter -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
          <link rel="stylesheet" type="text/css" href="reset.css" />
          <script type = "text/javascript" src="prototype.js"> </script>
          <script type = "text/javascript" src="basic.js"> </script>
          <script type = "text/javascript" src="barchart.js"> </script>
        <title>Balsamiq</title>
        <script type="text/javascript">
          addLoadEvent(function() {draw_barchart("BarChart4canvas", 233, 106, '[["#FF0101",0.45,0.8],["#0101FF",0.6,0.7]]')});

          addLoadEvent(function() {draw_barchart("BarChart6canvas", 155, 252, '[["#FF0101",0.45,0.8],["#0101FF",0.6,0.7]]')});

        </script>
      </head>

      <body>
        <div class="BarChart" id="BarChart4"
            style="position: absolute; font-size:10pt; text-align: left; left: 18px; top: 11px; width: 233px; 
                   padding:5px; outline: none; color: #010101; background-color: transparent; z-index: 0">
         <canvas id="BarChart4canvas" width="233" height="106">
         </canvas>
        </div>
        <div class="BarChart" id="BarChart6"
            style="position: absolute; font-size:10pt; text-align: left; left: 266px; top: 35px; width: 155px; 
                   padding:5px; outline: none; color: #010101; background-color: transparent; z-index: 1">
         <canvas id="BarChart6canvas" width="155" height="252">
         </canvas>
        </div>
      </body>
    </html>
    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    function draw_barchart(canvasid, w, h, json)
    {
    	var canvasel = document.getElementById(canvasid);
    	var ctx = canvasel.getContext('2d');

      ctx.fillStyle = "rgba(0,0,0,1.0)";
      ctx.strokeStyle = "rgba(0,0,0,1.0)";
      ctx.lineWidth = 8;
      ctx.lineCap = "round"; 
      ctx.fillRect(0,0,4,h);
      ctx.fillRect(0,h-4,w,h-4);

      var graphdata = json.evalJSON(true);
      var bars = graphdata.length;
      // first item is color
      var items = graphdata[0].length - 1;

      var percent = 1.0/((bars+1)*items+1);

      ctx.lineWidth = 2;

      var bar;
      var item;

      for (item = 1; item <= items; item++)
      {
        for (bar = 0; bar < bars; bar++)
        {
          ctx.fillStyle = graphdata[bar][0];
          ctx.fillRect(2,h*percent*(bar+(item-1)*3+1),w*graphdata[bar][item],percent*h);
          ctx.strokeRect(2,h*percent*(bar+(item-1)*3+1),w*graphdata[bar][item],percent*h);
        }        
      }
    }
        EOF
    filename = "barchart"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
