#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles datagrid" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="0" controlTypeID="com.balsamiq.mockups::DataGrid" x="41" y="26" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Name%2C%20Last%20Name%2C%20Age%2C%20Nickname%2C%20Kid%0AGiacomo%2C%20Guilizzoni%2C%2033%2C%20Peldi%2C%20%5B%5D%0AGuido%20Jack%2C%20Guilizzoni%2C%203%2C%20The%20Guids%2C%20%5Bx%5D%0AMariah%2C%20Maclachlan%2C%2034%2C%20Patata%2C%20%5B%5D</text>
          </controlProperties>
        </control>
        <control controlID="1" controlTypeID="com.balsamiq.mockups::DataGrid" x="41" y="153" w="511" h="154" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <selectedIndex>-1</selectedIndex>
            <color>12303802</color>
            <align>center</align>
            <verticalScrollbar>true</verticalScrollbar>
            <vLines>false</vLines>
            <underline>true</underline>
            <italic>true</italic>
            <hLines>true</hLines>
            <borderStyle>none</borderStyle>
            <text>Name%2C%20Last%20Name%2C%20Age%2C%20Nickname%2C%20Kid%0AGiacomo%2C%20Guilizzoni%2C%2033%2C%20Peldi%2C%20%5B%5D%0AGuido%20Jack%2C%20Guilizzoni%2C%203%2C%20The%20Guids%2C%20%5Bx%5D%0AMariah%2C%20Maclachlan%2C%2034%2C%20Patata%2C%20%5B%5D%0AA%2C%20Dood%2C%2012%2C%20Foop%21%2C%20%5Bx%5D</text>
            <size>16</size>
            <hasHeader>false</hasHeader>
            <alternateRowColor>15134199</alternateRowColor>
          </controlProperties>
        </control>
      </controls>
    </mockup>    


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <link rel="stylesheet" type="text/css" href="datagrid.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="DataGrid" id="DataGrid0"
        style="position: absolute; left: 41px; top: 26px; width:336px; height:118px;
        z-index: 0; outline: none; background-color: transparent;">
        <table cellspacing="0" style="border-collapse: collapse; border-spacing: 0;width:100%; height:100%; border: 1px solid #010101;">
        <tr class='header'><th><b>Name</b></th><th><b>Last Name</b></th><th><b>Age</b></th><th><b>Nickname</b></th><th><b>Kid</b></th></tr><tr class='row0'><td><b>Giacomo</b></td><td><b>Guilizzoni</b></td><td><b>33</b></td><td><b>Peldi</b></td><td><b>[]</b></td></tr><tr class='row1'><td><b>Guido Jack</b></td><td><b>Guilizzoni</b></td><td><b>3</b></td><td><b>The Guids</b></td><td><b>[x]</b></td></tr><tr class='row0'><td><b>Mariah</b></td><td><b>Maclachlan</b></td><td><b>34</b></td><td><b>Patata</b></td><td><b>[]</b></td></tr>
        </table>
    </div>
    <div class="DataGrid" id="DataGrid1"
        style="position: absolute; left: 41px; top: 153px; width:511px; height:154px;
        z-index: 1; outline: none; background-color: transparent;">
        <table cellspacing="0" style="border-collapse: collapse; border-spacing: 0;width:100%; height:100%; ;">
        <tr class='row0'><td><b><i><u>Name</u></i></b></td><td><b><i><u>Last Name</u></i></b></td><td><b><i><u>Age</u></i></b></td><td><b><i><u>Nickname</u></i></b></td><td><b><i><u>Kid</u></i></b></td></tr><tr class='row1'><td><b><i><u>Giacomo</u></i></b></td><td><b><i><u>Guilizzoni</u></i></b></td><td><b><i><u>33</u></i></b></td><td><b><i><u>Peldi</u></i></b></td><td><b><i><u>[]</u></i></b></td></tr><tr class='row0'><td><b><i><u>Guido Jack</u></i></b></td><td><b><i><u>Guilizzoni</u></i></b></td><td><b><i><u>3</u></i></b></td><td><b><i><u>The Guids</u></i></b></td><td><b><i><u>[x]</u></i></b></td></tr><tr class='row1'><td><b><i><u>Mariah</u></i></b></td><td><b><i><u>Maclachlan</u></i></b></td><td><b><i><u>34</u></i></b></td><td><b><i><u>Patata</u></i></b></td><td><b><i><u>[]</u></i></b></td></tr><tr class='row0'><td><b><i><u>A</u></i></b></td><td><b><i><u>Dood</u></i></b></td><td><b><i><u>12</u></i></b></td><td><b><i><u>Foop!</u></i></b></td><td><b><i><u>[x]</u></i></b></td></tr>
        </table>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    #DataGrid0 {
  font-size:9pt; 
  text-align: center; 
}

#DataGrid0 .header {
  background-color: #CCCCCC;
}


#DataGrid0 .row0 {
  background-color: RGBA(237,243,238,1.0);
}

#DataGrid0 .row1 {
  background-color: #FFFFFF;
}

#DataGrid0 td {
  border-left: 1px solid #010101;
}

#DataGrid0 th {
  border-left: 1px solid #010101;
}
#DataGrid1 {
  font-size:13pt; 
  text-align: center; 
}

#DataGrid1 .header {
  background-color: #CCCCCC;
}


#DataGrid1 .row0 {
  background-color: rgba(187,189,186,1.0);
}

#DataGrid1 .row1 {
  background-color: rgba(230,237,247,1.0);
}

#DataGrid1 td {
  border-bottom: 1px solid #010101;
}

#DataGrid1 th {
  border-bottom: 1px solid #010101;
}

    EOF
    js = <<-EOF

    EOF
    filename = "datagrid"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
