#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles accordion" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="2" controlTypeID="com.balsamiq.mockups::Accordion" x="27" y="7" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Item%20One%0AItem%20Two%0AItem%20Three%0AItem%20Four</text>
            <verticalScrollbar>false</verticalScrollbar>
          </controlProperties>
        </control>
        <control controlID="3" controlTypeID="com.balsamiq.mockups::Accordion" x="192" y="7" w="203" h="331" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>first%0Asecond%0Athird%0Afourth%0Afifth%0Asixth%0Aseventh</text>
            <selectedIndex>3</selectedIndex>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Generated by Balsamiq Exporter -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
          <link rel="stylesheet" type="text/css" href="reset.css" />
          <link rel="stylesheet" type="text/css" href="accordion.css" />
        <title>Balsamiq</title>
        <script type="text/javascript">
        </script>
      </head>

      <body>
        <div class="Accordion" id="Accordion2"
              style="position: absolute; left: 27px; top: 7px;  z-index: 0; font-size:10pt; width: 150px; height: 218px; outline: none; outline-top: 2px solid #202028;  background-color:transparent;">
                <div><a href="" id="Item One">Item One</a><div class="content"><p></p></div></div>
          <div><a href="" id="Item Two">Item Two</a><div class="content"><p></p></div></div>
          <div><a href="" id="Item Three">Item Three</a><div class="content"><p></p></div></div>
          <div><a href="" id="Item Four">Item Four</a><div class="content"><p></p></div></div>

        </div>
        <div class="Accordion" id="Accordion3"
              style="position: absolute; left: 192px; top: 7px;  z-index: 1; font-size:10pt; width: 203px; height: 331px; outline: none; outline-top: 2px solid #202028;  background-color:transparent;">
                <div><a href="" id="first">first</a><div class="content"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sem. Cras aliquam nunc et pede. Aenean euismod. Aenean placerat, ipsum quis cursus semper, tellus turpis facilisis nisi, non varius nunc sem eu ipsum. Quisque imperdiet dignissim sapien. Sed iaculis. Proin ullamcorper tortor eu neque. Quisque sed mauris mattis ante lacinia volutpat. Quisque id arcu. Fusce sit amet orci. Phasellus volutpat purus a erat. Ut condimentum</p></div></div>
          <div><a href="" id="second">second</a><div class="content"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sem. Cras aliquam nunc et pede. Aenean euismod. Aenean placerat, ipsum quis cursus semper, tellus turpis facilisis nisi, non varius nunc sem eu ipsum. Quisque imperdiet dignissim sapien. Sed iaculis. Proin ullamcorper tortor eu neque. Quisque sed mauris mattis ante lacinia volutpat. Quisque id arcu. Fusce sit amet orci. Phasellus volutpat purus a erat. Ut condimentum</p></div></div>
          <div><a href="" id="third">third</a><div class="content"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sem. Cras aliquam nunc et pede. Aenean euismod. Aenean placerat, ipsum quis cursus semper, tellus turpis facilisis nisi, non varius nunc sem eu ipsum. Quisque imperdiet dignissim sapien. Sed iaculis. Proin ullamcorper tortor eu neque. Quisque sed mauris mattis ante lacinia volutpat. Quisque id arcu. Fusce sit amet orci. Phasellus volutpat purus a erat. Ut condimentum</p></div></div>
          <div><a href="" id="fourth">fourth</a><div class="content"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sem. Cras aliquam nunc et pede. Aenean euismod. Aenean placerat, ipsum quis cursus semper, tellus turpis facilisis nisi, non varius nunc sem eu ipsum. Quisque imperdiet dignissim sapien. Sed iaculis. Proin ullamcorper tortor eu neque. Quisque sed mauris mattis ante lacinia volutpat. Quisque id arcu. Fusce sit amet orci. Phasellus volutpat purus a erat. Ut condimentum</p></div></div>
          <div><a href="" id="fifth">fifth</a><div class="content"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sem. Cras aliquam nunc et pede. Aenean euismod. Aenean placerat, ipsum quis cursus semper, tellus turpis facilisis nisi, non varius nunc sem eu ipsum. Quisque imperdiet dignissim sapien. Sed iaculis. Proin ullamcorper tortor eu neque. Quisque sed mauris mattis ante lacinia volutpat. Quisque id arcu. Fusce sit amet orci. Phasellus volutpat purus a erat. Ut condimentum</p></div></div>
          <div><a href="" id="sixth">sixth</a><div class="content"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sem. Cras aliquam nunc et pede. Aenean euismod. Aenean placerat, ipsum quis cursus semper, tellus turpis facilisis nisi, non varius nunc sem eu ipsum. Quisque imperdiet dignissim sapien. Sed iaculis. Proin ullamcorper tortor eu neque. Quisque sed mauris mattis ante lacinia volutpat. Quisque id arcu. Fusce sit amet orci. Phasellus volutpat purus a erat. Ut condimentum</p></div></div>
          <div><a href="" id="seventh">seventh</a><div class="content"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sem. Cras aliquam nunc et pede. Aenean euismod. Aenean placerat, ipsum quis cursus semper, tellus turpis facilisis nisi, non varius nunc sem eu ipsum. Quisque imperdiet dignissim sapien. Sed iaculis. Proin ullamcorper tortor eu neque. Quisque sed mauris mattis ante lacinia volutpat. Quisque id arcu. Fusce sit amet orci. Phasellus volutpat purus a erat. Ut condimentum</p></div></div>

        </div>
      </body>
    </html>
    EOF
    css = <<-EOF

#Accordion2 div {
  text-align: left;
  height: 25%;
  overflow: hidden;
}

#Accordion2 .content {
  height: 0px;
  overflow: hidden;
  outline: none;
}

#Accordion2:hover .content {
  height: 0px;
  overflow: hidden;
  outline: none;
}

#Accordion2:hover > div {
  height: 10%;
  overflow: hidden;
}

#Accordion2:hover div:hover .content {
  height: 100%;
  overflow: auto;
  background-color: none;
}

#Accordion2:hover div:hover p {
  margin: 5px;
}

#Accordion2:hover > div:hover {
  text-align: left;
  height: 70%;
  background-color: #AAEEBB;
  overflow: hidden;
}

#Accordion2 a {
  padding-left:10px;
  padding-top:5px;
  padding-bottom:5px;
  display: block;
  color: #010101;
  text-decoration: none;
}

#Accordion2:hover a {
  padding-top:2px;
  padding-bottom:2px;
}

#Accordion2 a:hover {
  color: #010101;
}

#Accordion3 div {
  text-align: left;
  height: 14%;
  overflow: hidden;
}

#Accordion3 .content {
  height: 0px;
  overflow: hidden;
  outline: none;
}

#Accordion3:hover .content {
  height: 0px;
  overflow: hidden;
  outline: none;
}

#Accordion3:hover > div {
  height: 10%;
  overflow: hidden;
}

#Accordion3:hover div:hover .content {
  height: 100%;
  overflow: auto;
  background-color: none;
}

#Accordion3:hover div:hover p {
  margin: 5px;
}

#Accordion3:hover > div:hover {
  text-align: left;
  height: 38%;
  background-color: #AAEEBB;
  overflow: hidden;
}

#Accordion3 a {
  padding-left:10px;
  padding-top:5px;
  padding-bottom:5px;
  display: block;
  color: #010101;
  text-decoration: none;
}

#Accordion3:hover a {
  padding-top:2px;
  padding-bottom:2px;
}

#Accordion3 a:hover {
  color: #010101;
}

    EOF
    js = <<-EOF

    EOF
    filename = "accordion"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
