#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles vsplitter" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="2" controlTypeID="com.balsamiq.mockups::VSplitter" x="36" y="64" w="-1" h="-1" zOrder="2" locked="false" isInGroup="-1"/>
        <control controlID="3" controlTypeID="com.balsamiq.mockups::VSplitter" x="34" y="94" w="454" h="-1" zOrder="3" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
      <div class="VSplitter"
        style="position: absolute; font-size:10pt; text-align: left; left: 36px; top: 64px; 
        width: 100px; height: 2px; z-index: 2; outline: none; background-color: #010101">
      </div>
      <div class="VSplitter"
        style="position: absolute; font-size:10pt; text-align: left; left: 36px; top: 74px; 
        width: 100px; height: 2px; z-index: 2; outline: none; background-color: #010101">
      </div>
      <div class="VSplitter"
        style="position: absolute; font-size:10pt; text-align: left; left: 34px; top: 94px; 
        width: 454px; height: 2px; z-index: 3; outline: none; background-color: #010101">
      </div>
      <div class="VSplitter"
        style="position: absolute; font-size:10pt; text-align: left; left: 34px; top: 104px; 
        width: 454px; height: 2px; z-index: 3; outline: none; background-color: #010101">
      </div>
  </body>
</html>

    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    EOF
    filename = "vsplitter"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
