#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles videoplayer" do
    data = <<-EOF
    <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="60" controlTypeID="com.balsamiq.mockups::VideoPlayer" x="36" y="17" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>
    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Generated by Balsamiq Exporter -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <link rel="stylesheet" type="text/css" href="reset.css" />
        <title>Balsamiq</title>
        <script type="text/javascript">
        </script>
      </head>

      <body>
        <div class="VideoPlayer" id="VideoPlayer60"
            style="position: absolute; font-size:10pt; text-align: left; left: 36px; top: 17px; width: 300px; height: 200px; z-index: 0">
          <object width="300" height="200">
            <param name="movie" value="http://www.youtube.com/v/y-LhyAVzDBI&hl=en&fs=1"></param>
            <param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param>
            <embed src="http://www.youtube.com/v/y-LhyAVzDBI&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="300" height="200"></embed>
          </object>
        </div>
      </body>
    </html>
    EOF
    css = <<-EOF
    EOF
    js = <<-EOF
    EOF
    filename = "videoplayer"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

  # this should be the last test
  it "creates a basic.js and reset.css files" do
    File.exists?("basic.js").should == true
    File.exists?("reset.css").should == true
    File.delete("basic.js").should == 1
    File.delete("reset.css").should == 1
  end      
end
