#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles list" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="8" controlTypeID="com.balsamiq.mockups::List" x="47" y="20" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Item%20One%0AItem%20Two%0AItem%20Three</text>
          </controlProperties>
        </control>
        <control controlID="9" controlTypeID="com.balsamiq.mockups::List" x="195" y="22" w="100" h="157" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Item%20One%0AItem%20Two%0AItem%20Three%0AItem%20Four%0AItem%20Five%0AItem%20Six</text>
            <selectedIndex>-1</selectedIndex>
            <verticalScrollbar>true</verticalScrollbar>
            <hasHeader>true</hasHeader>
            <alternateRowColor>15594478</alternateRowColor>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <link rel="stylesheet" type="text/css" href="list.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="List" id="List8"
        style="position: absolute; left: 47px; top: 20px; width:100px; height:126px;
        z-index: 0; background-color: transparent;">
        <table cellspacing="0" style="border-collapse: collapse; border-spacing: 0;width:100%;">
        <tr class='row0'><td><b>Item One</b></td></tr><tr class='row1'><td><b>Item Two</b></td></tr><tr class='row0'><td><b>Item Three</b></td></tr>
        </table>
    </div>
    <div class="List" id="List9"
        style="position: absolute; left: 195px; top: 22px; width:100px; height:157px;
        z-index: 1; background-color: transparent;">
        <table cellspacing="0" style="border-collapse: collapse; border-spacing: 0;width:100%;">
        <tr class='header'><th><b>Item One</b></th></tr><tr class='row0'><td><b>Item Two</b></td></tr><tr class='row1'><td><b>Item Three</b></td></tr><tr class='row0'><td><b>Item Four</b></td></tr><tr class='row1'><td><b>Item Five</b></td></tr><tr class='row0'><td><b>Item Six</b></td></tr>
        </table>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    #List8 {
  font-size:9pt; 
  text-align: center; 
}

#List8 .header {
  background-color: #CCCCCC;
}


#List8 .row0 {
  background-color: #FFFFFF;
}

#List8 .row1 {
  background-color: #FFFFFF;
}
#List9 {
  font-size:9pt; 
  text-align: center; 
}

#List9 .header {
  background-color: #CCCCCC;
}


#List9 .row0 {
  background-color: #FFFFFF;
}

#List9 .row1 {
  background-color: rgba(237,243,238,1.0);
}

    EOF
    js = <<-EOF

    EOF
    filename = "list"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
