#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles linkbar" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="5" controlTypeID="com.balsamiq.mockups::LinkBar" x="55" y="28" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Home%2CProducts%2CCompany%2CBlog</text>
          </controlProperties>
        </control>
        <control controlID="6" controlTypeID="com.balsamiq.mockups::LinkBar" x="54" y="70" w="-1" h="-1" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Home%2CProducts%2CCompany%2CBlog%2C%20foo%21</text>
            <italic>true</italic>
            <size>32</size>
            <underline>true</underline>
            <bold>false</bold>
            <align>right</align>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <link rel="stylesheet" type="text/css" href="linkbar.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="LinkBar" id="LinkBar5";
        style="position: absolute; font-size:9pt; text-align: center; left: 55px; top: 28px;
        z-index: 0; outline: none; background-color: transparent; color: #010101;">
        <span><a href=''><b>Home</b></a></span>|<span><a href=''><b>Products</b></a></span>|<span><a href=''><b>Company</b></a></span>|<span><a href=''><b>Blog</b></a></span>
    </div>
    <div class="LinkBar" id="LinkBar6";
        style="position: absolute; font-size:29pt; text-align: right; left: 54px; top: 70px;
        z-index: 1; outline: none; background-color: transparent; color: #010101;">
        <span><a href=''><i><u>Home</u></i></a></span>|<span><a href=''><i><u>Products</u></i></a></span>|<span><a href=''><i><u>Company</u></i></a></span>|<span><a href=''><i><u>Blog</u></i></a></span>|<span><a href=''><i><u> foo!</u></i></a></span>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    .LinkBar span {
  margin: 5px; 
}

    EOF
    js = <<-EOF

    EOF
    filename = "linkbar"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
