#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles paragraph" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="16" controlTypeID="com.balsamiq.mockups::Paragraph" x="294" y="26" w="-1" h="-1" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <italic>false</italic>
            <underline>false</underline>
            <align>center</align>
            <text>A%20paragraph%20of%20text.%0AA%20second%20row%20of%20text.%0AYet%20another%20row%20of%20text%21</text>
            <size>16</size>
            <bold>false</bold>
            <color>128</color>
          </controlProperties>
        </control>
        <control controlID="15" controlTypeID="com.balsamiq.mockups::Paragraph" x="38" y="23" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>A%20paragraph%20of%20text.%0AA%20second%20row%20of%20text.</text>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="Paragraph" id="Paragraph16";
        style="position: absolute; font-size:13pt; text-align: center; left: 294px; top: 26px;
        z-index: 1; outline: none; background-color: transparent; color: rgba(0,0,128,1.0);">
        <p class='text'>A paragraph of text.</p>
<p class='text'>A second row of text.</p>
<p class='text'>Yet another row of text!</p>
    </div>
    <div class="Paragraph" id="Paragraph15";
        style="position: absolute; font-size:9pt; text-align: center; left: 38px; top: 23px;
        z-index: 0; outline: none; background-color: transparent; color: #010101;">
        <p class='text'><b>A paragraph of text.</b></p>
<p class='text'><b>A second row of text.</b></p>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    EOF
    filename = "paragraph"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
