#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles progressbar" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="18" controlTypeID="com.balsamiq.mockups::ProgressBar" x="41" y="18" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <indeterminate>false</indeterminate>
          </controlProperties>
        </control>
        <control controlID="19" controlTypeID="com.balsamiq.mockups::ProgressBar" x="39" y="56" w="270" h="50" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <script type = "text/javascript" src="basic.js"> </script>
      <script type = "text/javascript" src="progressbar.js"> </script>
    <title>Balsamiq</title>
    <script type="text/javascript">
      addLoadEvent(function() {ProgressBar.setup("ProgressBar18bar", 100, 0)});

      addLoadEvent(function() {ProgressBar.setup("ProgressBar19bar", 270, 0)});

    </script>
  </head>

  <body>
    <div class="ProgressBar" id="ProgressBar18";
        style="position: absolute; font-size:12px; text-align: left; left: 41px; top: 18px; width: 100px; height: 16px;
        z-index: 0; overflow: hidden;">
      <div class="ProgressBar" id="ProgressBar18bar";
          style="position: absolute; font-size:12px; text-align: left; left: 0px; top: 0px; height: 16px;
          z-index: 0; background-color: #AAEEBB; overflow: hidden;">
      </div>
    </div>
    <div class="ProgressBar" id="ProgressBar19";
        style="position: absolute; font-size:12px; text-align: left; left: 39px; top: 56px; width: 270px; height: 46px;
        z-index: 1; overflow: hidden;">
      <div class="ProgressBar" id="ProgressBar19bar";
          style="position: absolute; font-size:12px; text-align: left; left: 0px; top: 0px; height: 46px;
          z-index: 1; background-color: #AAEEBB; overflow: hidden;">
      </div>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    /* Generated by Balsamiq Exporter */
* {
  vertical-align: baseline;
  font-weight: inherit;
  font-family: inherit;
  font-style: inherit;
  font-size: 100%;
  border: 0 none;
  outline: 0;
  padding: 0;
  margin: 0;
}

body {
  background-color: #f8f4ed;
  font-family: "Comic Sans MS", Arial,sans-serif;
  color: #010101;
}

div {
  background-color: #ffffff;
  outline: 2px solid #202028;
  text-align: center;
}

a {
  color:#0101ff;
}

a:link {
  color:#0101ff;
}

a:hover {
  color:#FD0101;
}

    EOF
    js = <<-EOF

var ProgressBar =
{
  setup : function(id, width, percent)
  {
    var div = document.getElementById(id);
    setTimeout(function() {ProgressBar.update(div, width, percent)}, 1);
  },
  update : function(div, width, percent)
  {
    div.style.width = parseInt(percent*width/100.0) + "px";
    if (percent < 100)
    {
      percent++;
      setTimeout(function() {ProgressBar.update(div, width + 1, percent)}, 50);
    }
  },
}

    EOF
    filename = "progressbar"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
