#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles breadcrumbs" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="0" controlTypeID="com.balsamiq.mockups::BreadCrumbs" x="22" y="16" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Home%2C%20Products%2C%20Xyz%2C%20Features</text>
            <bold>false</bold>
          </controlProperties>
        </control>
        <control controlID="1" controlTypeID="com.balsamiq.mockups::BreadCrumbs" x="22" y="40" w="-1" h="-1" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>This...%2C%20That...%2C%20The%20Other%20Thing...%2C%20And%20Now...</text>
            <italic>true</italic>
            <size>18</size>
            <underline>true</underline>
            <align>center</align>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <link rel="stylesheet" type="text/css" href="breadcrumbs.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="BreadCrumbs" id="0"
          style="position: absolute; left: 22px; top: 16px;  z-index: 0; font-size:11pt">
          <a href="">Home</a> > <a  href="">Products</a> > <a  href="">Xyz</a> > Features
    </div>
    <div class="BreadCrumbs" id="1"
          style="position: absolute; left: 22px; top: 40px;  z-index: 1; font-size:16pt">
          <strong><em><u><a href="">This...</a></u></em></strong> > <strong><em><u><a  href="">That...</a></u></em></strong> > <strong><em><u><a  href="">The Other Thing...</a></u></em></strong> > <strong><em><u>And Now...</u></em></strong>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

.BreadCrumbs {
background-color: transparent;
outline: none
}

    EOF
    js = <<-EOF

    EOF
    filename = "breadcrumbs"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
