#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles modalscreen" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="4" controlTypeID="com.balsamiq.mockups::ModalScreen" x="20" y="18" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="5" controlTypeID="com.balsamiq.mockups::ModalScreen" x="366" y="21" w="126" h="86" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="ModalScreen" id="ModalScreen4"
        style="position: absolute; font-size:10pt; outline: none; background-color: #8c8a86; text-align: left; left: 20px; top: 18px; width: 320px; height: 240px; z-index: 0">
    </div>
    <div class="ModalScreen" id="ModalScreen5"
        style="position: absolute; font-size:10pt; outline: none; background-color: #8c8a86; text-align: left; left: 366px; top: 21px; width: 126px; height: 86px; z-index: 1">
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    EOF
    filename = "modalscreen"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
