#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles calendar" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="0" controlTypeID="com.balsamiq.mockups::Calendar" x="216" y="32" w="259" h="225" zOrder="0" locked="false" isInGroup="-1"/>
        <control controlID="1" controlTypeID="com.balsamiq.mockups::Calendar" x="91" y="32" w="-1" h="-1" zOrder="1" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Generated by Balsamiq Exporter -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
          <link rel="stylesheet" type="text/css" href="reset.css" />
          <link rel="stylesheet" type="text/css" href="calendar.css" />
        <title>Balsamiq</title>
        <script type="text/javascript">
        </script>
      </head>

      <body>
        <div class="Calendar" id="Calendar0" 
            style="position: absolute; left: 216px; top: 32px; 
            width: 259px; height: 225px; z-index: 0;" >
          <div class="balsamiq-calendar-caption" style="font-size:8pt; position:relative; width:100%; height: 16%; outline-bottom: 2px solid #010101">
            <a href="#" title="next month" class="nav">&laquo;</a> <strong>JAN 9</strong> <a href="#" title="next month" class="nav">&raquo;</a>
          </div>
          <div class="balsamiq-calendar-headerdiv" style="font-size:8pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-header">S</div>
            <div class="balsamiq-calendar-header">M</div>
            <div class="balsamiq-calendar-header">T</div>
            <div class="balsamiq-calendar-header">W</div>
            <div class="balsamiq-calendar-header">T</div>
            <div class="balsamiq-calendar-header">F</div>
            <div class="balsamiq-calendar-header">S</div>
          </div>
          <div class="balsamiq-calendar-rowdiv" style="font-size:7pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-element">  </div>
            <div class="balsamiq-calendar-element">  </div>
            <div class="balsamiq-calendar-element"> 1</div>
            <div class="balsamiq-calendar-element"> 2</div>
            <div class="balsamiq-calendar-element"> 3</div>
            <div class="balsamiq-calendar-element"> 4</div>
            <div class="balsamiq-calendar-element"> 5</div>
          </div>
          <div class="balsamiq-calendar-rowdiv" style="font-size:7pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-element"> 6</div>
            <div class="balsamiq-calendar-element"> 7</div>
            <div class="balsamiq-calendar-element"> 8</div>
            <div class="balsamiq-calendar-element"> 9</div>
            <div class="balsamiq-calendar-element">10</div>
            <div class="balsamiq-calendar-element">11</div>
            <div class="balsamiq-calendar-element">12</div>
          </div>
          <div class="balsamiq-calendar-rowdiv" style="font-size:7pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-element">13</div>
            <div class="balsamiq-calendar-element">14</div>
            <div class="balsamiq-calendar-element">15</div>
            <div class="balsamiq-calendar-element">16</div>
            <div class="balsamiq-calendar-element">17</div>
            <div class="balsamiq-calendar-element">18</div>
            <div class="balsamiq-calendar-element">19</div>
          </div>
          <div class="balsamiq-calendar-rowdiv" style="font-size:7pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-element">20</div>
            <div class="balsamiq-calendar-element">21</div>
            <div class="balsamiq-calendar-element">22</div>
            <div class="balsamiq-calendar-element">23</div>
            <div class="balsamiq-calendar-element">24</div>
            <div class="balsamiq-calendar-element">25</div>
            <div class="balsamiq-calendar-element">26</div>
          </div>
          <div class="balsamiq-calendar-rowdiv" style="font-size:7pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-element">27</div>
            <div class="balsamiq-calendar-element">28</div>
            <div class="balsamiq-calendar-element">29</div>
            <div class="balsamiq-calendar-element">30</div>
            <div class="balsamiq-calendar-element">31</div>
            <div class="balsamiq-calendar-element"></div>
            <div class="balsamiq-calendar-element"></div>
          </div>
        </div>
        <div class="Calendar" id="Calendar1" 
            style="position: absolute; left: 91px; top: 32px; 
            width: 96px; height: 96px; z-index: 1;" >
          <div class="balsamiq-calendar-caption" style="font-size:8pt; position:relative; width:100%; height: 16%; outline-bottom: 2px solid #010101">
            <a href="#" title="next month" class="nav">&laquo;</a> <strong>JAN 9</strong> <a href="#" title="next month" class="nav">&raquo;</a>
          </div>
          <div class="balsamiq-calendar-headerdiv" style="font-size:8pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-header">S</div>
            <div class="balsamiq-calendar-header">M</div>
            <div class="balsamiq-calendar-header">T</div>
            <div class="balsamiq-calendar-header">W</div>
            <div class="balsamiq-calendar-header">T</div>
            <div class="balsamiq-calendar-header">F</div>
            <div class="balsamiq-calendar-header">S</div>
          </div>
          <div class="balsamiq-calendar-rowdiv" style="font-size:7pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-element">  </div>
            <div class="balsamiq-calendar-element">  </div>
            <div class="balsamiq-calendar-element"> 1</div>
            <div class="balsamiq-calendar-element"> 2</div>
            <div class="balsamiq-calendar-element"> 3</div>
            <div class="balsamiq-calendar-element"> 4</div>
            <div class="balsamiq-calendar-element"> 5</div>
          </div>
          <div class="balsamiq-calendar-rowdiv" style="font-size:7pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-element"> 6</div>
            <div class="balsamiq-calendar-element"> 7</div>
            <div class="balsamiq-calendar-element"> 8</div>
            <div class="balsamiq-calendar-element"> 9</div>
            <div class="balsamiq-calendar-element">10</div>
            <div class="balsamiq-calendar-element">11</div>
            <div class="balsamiq-calendar-element">12</div>
          </div>
          <div class="balsamiq-calendar-rowdiv" style="font-size:7pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-element">13</div>
            <div class="balsamiq-calendar-element">14</div>
            <div class="balsamiq-calendar-element">15</div>
            <div class="balsamiq-calendar-element">16</div>
            <div class="balsamiq-calendar-element">17</div>
            <div class="balsamiq-calendar-element">18</div>
            <div class="balsamiq-calendar-element">19</div>
          </div>
          <div class="balsamiq-calendar-rowdiv" style="font-size:7pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-element">20</div>
            <div class="balsamiq-calendar-element">21</div>
            <div class="balsamiq-calendar-element">22</div>
            <div class="balsamiq-calendar-element">23</div>
            <div class="balsamiq-calendar-element">24</div>
            <div class="balsamiq-calendar-element">25</div>
            <div class="balsamiq-calendar-element">26</div>
          </div>
          <div class="balsamiq-calendar-rowdiv" style="font-size:7pt; width:100%; height: 14%; outline: none">
            <div class="balsamiq-calendar-spacer"></div>
            <div class="balsamiq-calendar-element">27</div>
            <div class="balsamiq-calendar-element">28</div>
            <div class="balsamiq-calendar-element">29</div>
            <div class="balsamiq-calendar-element">30</div>
            <div class="balsamiq-calendar-element">31</div>
            <div class="balsamiq-calendar-element"></div>
            <div class="balsamiq-calendar-element"></div>
          </div>
        </div>
      </body>
    </html>
    EOF
    css = <<-EOF

.balsamiq-calendar-spacer {
  float: left;
  width:9%; 
  height: 100%; 
  outline: none
}

.balsamiq-calendar-element, .balsamiq-calendar-header {
  float: left;
  width:12%; 
  height: 100%; 
  outline: none
}

.balsamiq-calendar-element:hover {
  background-color: #AAEEBB;
}

.balsamiq-calendar-caption a {
  color:#010101;
  text-decoration: none;
}

.balsamiq-calendar-spacer {
  float: left;
  width:9%; 
  height: 100%; 
  outline: none
}

.balsamiq-calendar-element, .balsamiq-calendar-header {
  float: left;
  width:12%; 
  height: 100%; 
  outline: none
}

.balsamiq-calendar-element:hover {
  background-color: #AAEEBB;
}

.balsamiq-calendar-caption a {
  color:#010101;
  text-decoration: none;
}

    EOF
    js = <<-EOF

    EOF
    filename = "calendar"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
