#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles combobox" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="19" controlTypeID="com.balsamiq.mockups::ComboBox" x="102" y="41" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>ComboBox</text>
          </controlProperties>
        </control>
        <control controlID="20" controlTypeID="com.balsamiq.mockups::ComboBox" x="103" y="77" w="223" h="-1" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Another%20Combo%20Box%0AFoo%21%0ABar%21%0AMeep%21</text>
            <state>up</state>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <link rel="stylesheet" type="text/css" href="combobox.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="ComboBox" id="ComboBox19" 
          style="position: absolute; left: 102px; top: 41px; width: 92px; z-index: 0;
          font-size:10pt; outline:none; background-color: transparent;">
      <div class="balsamiq_combo" style="text-align: left; z-index: 1">
        ComboBox
      </div>
    </div>
    <div class="ComboBox" id="ComboBox20" 
          style="position: absolute; left: 103px; top: 77px; width: 223px; z-index: 1;
          font-size:10pt; outline:none; background-color: transparent;">
      <div class="balsamiq_combo" style="text-align: left; z-index: 2">
        Another Combo Box
        <div class="balsamiq_combo_element" style="text-align: left; outline: none; z-index: 3">
          Foo!
        </div>
        <div class="balsamiq_combo_element" style="text-align: left; outline: none; z-index: 3">
          Bar!
        </div>
        <div class="balsamiq_combo_element" style="text-align: left; outline: none; z-index: 3">
          Meep!
        </div>
      </div>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    .balsamiq_combo {
  background-color: #CCCCCC;
}

.balsamiq_combo:hover {
  background-color: #AAEEBB;
}

.balsamiq_combo:hover .balsamiq_combo_element{
  display:block;
}

.balsamiq_combo_element {
  display:none;
}

.balsamiq_combo_element:hover {
  background-color: #CCCCCC;
}

    EOF
    js = <<-EOF

    EOF
    filename = "combobox"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
