#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles hsplitter" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="4" controlTypeID="com.balsamiq.mockups::HSplitter" x="205" y="290" w="-1" h="-1" zOrder="4" locked="false" isInGroup="-1"/>
        <control controlID="5" controlTypeID="com.balsamiq.mockups::HSplitter" x="241" y="19" w="-1" h="404" zOrder="5" locked="false" isInGroup="-1"/>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="HSplitter"
      style="position: absolute; font-size:10pt; text-align: left; left: 205px; top: 290px; 
      width: 2px; height: 100px; z-index: 4; outline: none; background-color: #010101">
    </div>
    <div class="HSplitter"
      style="position: absolute; font-size:10pt; text-align: left; left: 215px; top: 290px; 
      width: 2px; height: 100px; z-index: 4; outline: none; background-color: #010101">
    </div>
    <div class="HSplitter"
      style="position: absolute; font-size:10pt; text-align: left; left: 241px; top: 19px; 
      width: 2px; height: 404px; z-index: 5; outline: none; background-color: #010101">
    </div>
    <div class="HSplitter"
      style="position: absolute; font-size:10pt; text-align: left; left: 251px; top: 19px; 
      width: 2px; height: 404px; z-index: 5; outline: none; background-color: #010101">
    </div>
  </body>
</html>

    EOF
    css = <<-EOF

    EOF
    js = <<-EOF

    EOF
    filename = "hsplitter"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
