#!/usr/bin/env ruby
      
# Copyright (c) 2009 Cory Ondrejka. All rights reserved.
# See License.txt for licensing details.

require "#{File.dirname(__FILE__)}/../testing_file_support"

describe BalsamiqControlParser do
  it "properly handles multilinebutton" do
    data = <<-EOF
            <mockup version="1.0" skin="sketch">
      <controls>
        <control controlID="6" controlTypeID="com.balsamiq.mockups::MultilineButton" x="29" y="17" w="-1" h="-1" zOrder="0" locked="false" isInGroup="-1">
          <controlProperties>
            <text>Multiline%20Button%0ASecond%20line%20of%20text</text>
          </controlProperties>
        </control>
        <control controlID="7" controlTypeID="com.balsamiq.mockups::MultilineButton" x="92" y="127" w="205" h="172" zOrder="1" locked="false" isInGroup="-1">
          <controlProperties>
            <text>The%20Big%20Line%20of%20Text%0ASome%20more%20text%0Aand%20yet%20more%21</text>
            <backgroundAlpha>0.5</backgroundAlpha>
            <color>16711680</color>
          </controlProperties>
        </control>
      </controls>
    </mockup>


    EOF
    html = <<-EOF
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Balsamiq Exporter -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="reset.css" />
      <link rel="stylesheet" type="text/css" href="multilinebutton.css" />
    <title>Balsamiq</title>
    <script type="text/javascript">
    </script>
  </head>

  <body>
    <div class="MultilineButton" id="MultilineButton6"
        style="position: absolute; left: 29px; top: 17px; width: 155px; height: 78px;
        z-index: 0; outline: none; background-color: transparent;">
      <div class="MultilineButton"
          style="position: absolute; left:1px; top:1px; width: 157px; height: 80px;
            z-index: 0; outline: none; background-color: RGBA(255,255,255,1.0); opacity: 1.0";>
      </div>
      <div class="MultilineButton"
          style="position: absolute; left: 0px; top: 0px; width: 155px; height: 78px;
            z-index: 0; border: 2px solid #010101; outline: none; background-color: transparent";>
      </div>
      <div style="position: absolute; top: 50%; margin-top: -25%; width: 100%;
        z-index: 0; outline: none; background-color: transparent;">
        <p class="first">Multiline Button</p>
        <p class='rest'>Second line of text</p>
      </div>
    </div>
    <div class="MultilineButton" id="MultilineButton7"
        style="position: absolute; left: 92px; top: 127px; width: 205px; height: 172px;
        z-index: 1; outline: none; background-color: transparent;">
      <div class="MultilineButton"
          style="position: absolute; left:1px; top:1px; width: 207px; height: 174px;
            z-index: 1; outline: none; background-color: rgba(255,0,0,1.0); opacity: 0.5";>
      </div>
      <div class="MultilineButton"
          style="position: absolute; left: 0px; top: 0px; width: 205px; height: 172px;
            z-index: 1; border: 2px solid #010101; outline: none; background-color: transparent";>
      </div>
      <div style="position: absolute; top: 50%; margin-top: -25%; width: 100%;
        z-index: 1; outline: none; background-color: transparent;">
        <p class="first">The Big Line of Text</p>
        <p class='rest'>Some more text</p>
<p class='rest'>and yet more!</p>
      </div>
    </div>
  </body>
</html>

    EOF
    css = <<-EOF
    .MultilineButton {
-moz-border-radius: 16px;
-webkit-border-radius:16px;
border-radius: 16px;
}

.MultilineButton .first {
  font-size: 11pt;
}

.MultilineButton .rest {
  font-size: 9pt;
}
.MultilineButton {
-moz-border-radius: 16px;
-webkit-border-radius:16px;
border-radius: 16px;
}

.MultilineButton .first {
  font-size: 11pt;
}

.MultilineButton .rest {
  font-size: 9pt;
}

    EOF
    js = <<-EOF

    EOF
    filename = "multilinebutton"
    TestingFileSupport::test_elements(filename, data, html, css, js, false)
  end

end
